package lk.ijse.pharmacy.util;

public enum Routes {
    LOGIN , SIGNIN , ADMINLOGIN , EMPLOYEE , SUPPLIER , ADMIN , CUSTOMER ,
    PLACEORDER , MEDICATION , EMPLOYEELOGIN ,
    ADDEMPLOYEE , UPDATEEMPLOYEE , DELETEEMPLOYEE ,
    ADDSUPPLIER , UPDATESUPPLIER , DELETESUPPLIER ,
    ADDCUSTOMER , UPDATECUSTOMER , DELETECUSTOMER ,
    ADDMEDICATION , UPDATEMEDICATION , DELETEMEDICATION ,
    ADDADMIN , UPDATEADMIN , DELETEADMIN
}
